### ISSUE TITLE
nVidia drivers issues

### ISSUE THREAD

**Issue by topas-rec** [QTodoTxt/QTodoTxt2#75]
Dear all,

after finding the master branch and launching that branch the app starts fine (Had issues with wrong branch before).
The gui frame shows up but nothing gets shown inside this frame:
![screenshot from 2017-10-09 21-04-45](https://user-images.githubusercontent.com/20391449/31354310-2ae295a4-ad36-11e7-99eb-dcb475a9a92f.png)

The console shows the following errors
`appmenu-qt: handleReparent 138 The given QWindow has no QMenuBar assigned
filteredTasks about to change in python
QOpenGLShader: could not create shader
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShaderProgram::uniformLocation( imageTexture ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""
QOpenGLShaderProgram::uniformLocation( matrix ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed: 
""
 [...]`

Did anyone got QTodoTxt2 running on ubuntu [16.04]?

**Comment by oroulet** [comment]
Looks like a Qt issue. I had it running on 17.10 and now it works fine on 17.10. But I do not have nvidia..

**Comment by davide125** [comment]
#72 should help with this

**Comment by topas-rec** [comment]
Thanks for reporting. I missed that progress out of scope of this issue.
I want to try #72 and will report.

**Comment by topas-rec** [comment]
@davide125:
#72 fixes this issue. Thanks for your help.
