### ISSUE TITLE
find solution for completion

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt2#1]

**Comment by oroulet** [comment]
@fuchsmich 
I get following error after your last 2 commits:
./qtodotxt
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:93:46: Unable to assign [undefined] to int
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:92:51: Unable to assign [undefined] to QString
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99: TypeError: Cannot read property '1' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.q

**Comment by oroulet** [comment]
@fuchsmich what is the status now? I does not seem to work for me..

**Comment by fuchsmich** [comment]
To me works (but not at the beginning of a line, have to modify the regex pattern for this to work).
In the middle of a line start typing a "(","+" or "@" then a list should pop up.

**Comment by fuchsmich** [comment]
...of course there is still a lot to do.

**Comment by oroulet** [comment]
does not work here.... 
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:99:46: Unable to assign [undefined] to int
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:98:51: Unable to assign [undefined] to QString
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:109: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/TaskLine.qml:109: TypeError: Property 'startsWith' of object (A) is not a function
I understand this as that you expect a QString but we get a javascript string.... what version of qt do you have? 5.7 here..

**Comment by fuchsmich** [comment]
I'm using 5.8 in Archlinux and Windows.

Ok, seems the 5.7 js-machine doesnt have this function. argh.

**Comment by fuchsmich** [comment]
...mabe we should support at least 5.6 which is the LTS version.
Will have to check, how to install multiple versions of qt.

**Comment by fuchsmich** [comment]
Hm, it should work with 5.7 also.
![qttt](https://cloud.githubusercontent.com/assets/2899761/25012101/c538b88a-206f-11e7-8739-734ae6b9cb3b.png)

I made a little change, maybe this helps. Just a minute.

**Comment by oroulet** [comment]
still cannot test: 
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/QTodoTxt.qml:250:31: Unable to assign [undefined] to QString
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/QTodoTxt.qml:250:31: Unable to assign [undefined] to QString
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:101: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:101: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:101: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:101: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:76: TypeError: Cannot read property 'text' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:77: TypeError: Cannot read property 'cursorPosition' of null

**Comment by fuchsmich** [comment]
please try again and post output with latest commit

**Comment by oroulet** [comment]
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/QTodoTxt.qml:250:31: Unable to assign [undefined] to QString
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/QTodoTxt.qml:250:31: Unable to assign [undefined] to QString
qml: -> string string
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:101: TypeError: Property 'startsWith' of object (A) is not a function
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:76: TypeError: Cannot read property 'text' of null
file:///home/olivier/dev/qml-qtodotxt/qtodotxt/qml/CompletionPopup.qml:77: TypeError: Cannot read property 'cursorPosition' of null

**Comment by oroulet** [comment]
must be some limitation of javascript engine in  qt 5.7
Can't we simply acces first character with str[0] in javascript?

**Comment by fuchsmich** [comment]
how about current one?

**Comment by oroulet** [comment]
What do you mean by current one? I pasted latest stack trace
Btw if the completion code get too complicated we should maybe push it to python... But python is probably slower than js...

**Comment by fuchsmich** [comment]
I replaced the "startsWith" method in last commit.

**Comment by oroulet** [comment]
works well now!! well done!. I will export projects, contexts and priorities as a property from mainController.
But for dates I propose to replace the old string based completion by a calendar widget popup. Do you give it a try?

**Comment by oroulet** [comment]
new property completionStrings implemented and satt as model. This seems to work very well!

**Comment by fuchsmich** [comment]
Yes, it's nice. :) The visual stuff, connecting the proper events for opening 
and closing and figuring out the keyboard handling took some time.

I will play around with the calendar widget but also 'd like to keep the 
completion strings. I'm sure there are some, who prefer typing strings then 
choosing the date from a widget.

**Comment by oroulet** [comment]
calendar widget looks very nice! good work as usual! With such a widget I do not think strings will be necessary, but we'll see...

**Comment by oroulet** [comment]
a small bug. If I choose 'due:' from autocompletion then the calendar pops up. But if I write 'due:' or get back to due: with backspace then not calendar pops up..

**Comment by oroulet** [comment]
and another bigger one: I select another task while the completion popup is visible then it stays visible and we get a coredump....

**Comment by fuchsmich** [comment]
> a small bug. If I choose 'due:' from autocompletion then the calendar pops up. But if I write 'due:' or get back to due: with backspace then not calendar pops up..

That's intended behaviour. The calendar opens only when you select "due:" from the Completionlist.

**Comment by oroulet** [comment]
It should not. Completion should appear on key press. Writing t: is faster without completion but you still want the calendar to pop up

**Comment by fuchsmich** [comment]
With some additional tweaking we could also use it in the search field.

**Comment by oroulet** [comment]
Yes

**Comment by oroulet** [comment]
not sure you need much tweaking... should work nicelly out of the box I
guess

**Comment by fuchsmich** [comment]
something's different with the cursorposition between textarea 
(taskedit) and textfield (searchbar).

Am 19.04.2017 um 16:37 schrieb oroulet:
> not sure you need much tweaking... should work nicelly out of the box I
> guess
> 
> On Wed, 19 Apr 2017 at 16:26 Olivier Roulet-Dubonnet <

**Comment by fuchsmich** [comment]
Found out that TextField changes cursorPosition *after* textChanged is 
emitted and TextArea *before*. o.O
Have no solution for this ad hoc...

Am 19.04.2017 um 16:37 schrieb oroulet:
> not sure you need much tweaking... should work nicelly out of the box I
> guess
> 
> On Wed, 19 Apr 2017 at 16:26 Olivier Roulet-Dubonnet <

**Comment by oroulet** [comment]
This sounds like a big to report to qt
